var annotated =
[
    [ "BCastEmitter", "class_b_cast_emitter.html", "class_b_cast_emitter" ],
    [ "BinaryMap< In1, In2, Out >", "class_binary_map.html", "class_binary_map" ],
    [ "BinaryOperator< In1, In2, Out >", "class_binary_operator.html", "class_binary_operator" ],
    [ "Collector", "class_collector.html", "class_collector" ],
    [ "Emitter", "class_emitter.html", null ],
    [ "FlatMap< In, Out >", "class_flat_map.html", "class_flat_map" ],
    [ "GroupParam", "class_group_param.html", null ],
    [ "InputOperator< Out >", "class_input_operator.html", "class_input_operator" ],
    [ "KeyValue< K, V >", "class_key_value.html", "class_key_value" ],
    [ "Map< In, Out >", "class_map.html", "class_map" ],
    [ "Operator", "class_operator.html", "class_operator" ],
    [ "OptionData", "struct_option_data.html", "struct_option_data" ],
    [ "OutputOperator< In >", "class_output_operator.html", "class_output_operator" ],
    [ "ParExecDF", "class_par_exec_d_f.html", "class_par_exec_d_f" ],
    [ "Pipe", "class_pipe.html", "class_pipe" ],
    [ "PReduce< In >", "class_p_reduce.html", "class_p_reduce" ],
    [ "PReduceFFNode< In >", "class_p_reduce_f_f_node.html", "class_p_reduce_f_f_node" ],
    [ "ReadFromFile< Out >", "class_read_from_file.html", "class_read_from_file" ],
    [ "ReadFromFileFFNode< Out >", "class_read_from_file_f_f_node.html", "class_read_from_file_f_f_node" ],
    [ "Reduce< In >", "class_reduce.html", "class_reduce" ],
    [ "RREmitter", "class_r_r_emitter.html", "class_r_r_emitter" ],
    [ "SemanticDAG", "class_semantic_d_a_g.html", "class_semantic_d_a_g" ],
    [ "SemDAGNode", "class_sem_d_a_g_node.html", "class_sem_d_a_g_node" ],
    [ "UnaryFlatMapFFNode< In, Out >", "class_unary_flat_map_f_f_node.html", "class_unary_flat_map_f_f_node" ],
    [ "UnaryMapFFNode< In, Out >", "class_unary_map_f_f_node.html", "class_unary_map_f_f_node" ],
    [ "UnaryOperator< In, Out >", "class_unary_operator.html", "class_unary_operator" ],
    [ "WindowParam", "class_window_param.html", null ],
    [ "WriteToDisk< In >", "class_write_to_disk.html", "class_write_to_disk" ],
    [ "WriteToDiskFFNode< In >", "class_write_to_disk_f_f_node.html", "class_write_to_disk_f_f_node" ]
];